const SVG_NS = "http://www.w3.org/2000/svg";

/*
 * Split-coast locations are valid JReferee unit locations, but standard.svg
 * has one visible region each for St Petersburg, Spain, and Bulgaria.
 *
 * These offsets are in the SVG viewBox coordinate system.
 */
const COAST_OFFSETS = {
  stpnc: { dx: 10, dy: -7 },
  stpsc: { dx: 8, dy: 9 },
  spanc: { dx: -5, dy: -3 },
  spasc: { dx: 5, dy: 4 },
  bulec: { dx: 4, dy: 1 },
  bulsc: { dx: -3, dy: 4 }
};

const NATION_COLORS = {
  AUSTRIA: "#c48f85",
  ENGLAND: "#7562b8",
  FRANCE: "#4b84cc",
  GERMANY: "#6f6f6f",
  ITALY: "#4f9a62",
  RUSSIA: "#a87e9f",
  TURKEY: "#d7ae4a"
};

const NEUTRAL_SUPPLY_CENTER_COLOR = "#f8fafc";
const SUPPLY_CENTER_OUTLINE_COLOR = "#111827";
const SUPPLY_CENTER_DOT_COLOR = "#ffffff";

/*
 * standard.svg's #layer5 marker groups were generated by Inkscape and do not
 * contain province data attributes. This maps their existing IDs to the
 * canonical Province names emitted by /api/board.
 *
 * Do not use StpNC, StpSC, SpaNC, SpaSC, BulEC, or BulSC here: supply-center
 * ownership is territory-wide, so JReferee emits Stp, Spa, and Bul.
 */
const SUPPLY_CENTER_INDICATORS = {
  "g5246": "Bel",
  "g5246-3": "Hol",
  "g5246-6": "Kie",
  "g5246-9": "Ber",
  "g5246-0": "Mun",
  "g5246-8": "Vie",
  "g5246-02": "Bud",
  "g5246-92": "Tri",
  "g5246-36": "Ser",
  "g5246-93": "Bul",
  "g5246-7": "Rum",
  "g5246-03": "Con",
  "g5246-63": "Ank",
  "g5246-5": "Smy",
  "g5246-56": "Sev",
  "g5246-74": "Mos",
  "g5246-84": "Stp",
  "g5246-2": "War",
  "g5246-926": "Ven",
  "g5246-04": "Rom",
  "g5246-72": "Nap",
  "g5246-1": "Tun",
  "g5246-94": "Mar",
  "g5246-77": "Spa",
  "g5246-776": "Por",
  "g5246-639": "Par",
  "g5246-939": "Bre",
  "g5246-50": "Lon",
  "g5246-561": "Lvp",
  "g5246-4": "Edi",
  "g5246-044": "Den",
  "g5246-17": "Swe",
  "g5246-178": "Nwy",
  "g5246-85": "Gre"
};

let board = null;
let svgRoot = null;
let selectedProvince = null;

/*
 * Expected API shape:
 *
 * {
 *   "year": 1901,
 *   "phase": "SPRING_MOVEMENT",
 *   "units": [
 *     { "nation": "ENGLAND", "type": "FLEET", "province": "Edi" }
 *   ],
 *   "supplyCenterOwners": {
 *     "Edi": "ENGLAND"
 *   }
 * }
 */
async function startViewer() {
  const [svgText, snapshot] = await Promise.all([
    fetch("/ui/maps/standard.svg")
      .then(requireOk)
      .then(response => response.text()),

    fetch("/api/board")
      .then(requireOk)
      .then(response => response.json())
  ]);

  board = indexSnapshot(snapshot);

  const host = document.querySelector("#map-host");
  host.innerHTML = svgText;

  svgRoot = host.querySelector("svg");
  svgRoot.classList.add("board-svg");

  installProvinceInteractions();
  renderSupplyCenterOwners();
  renderUnits();
  renderTurnLabel();
  clearSelection();

  document.querySelector("#reset-selection")
    .addEventListener("click", clearSelection);

  document.addEventListener("keydown", event => {
    if (event.key === "Escape") {
      clearSelection();
    }
  });
}

function requireOk(response) {
  if (!response.ok) {
    throw new Error(
      `Request failed: ${response.status} ${response.statusText}`
    );
  }

  return response;
}

function indexSnapshot(snapshot) {
  return {
    ...snapshot,
    unitsByLocation: new Map(
      snapshot.units.map(unit => [keyOf(unit.province), unit])
    )
  };
}

/*
 * JReferee uses mixed-case land codes and uppercase sea codes. SVG IDs are
 * lowercase. Normalizing to lowercase makes the two compatible.
 */
function keyOf(province) {
  return province.toLowerCase();
}

/*
 * A click on a coast-specific location selects its one visible parent region.
 */
function visibleProvinceKey(province) {
  const key = keyOf(province);

  const parents = {
    stpnc: "stp",
    stpsc: "stp",
    spanc: "spa",
    spasc: "spa",
    bulec: "bul",
    bulsc: "bul"
  };

  return parents[key] ?? key;
}

function installProvinceInteractions() {
  const provincePaths = svgRoot.querySelectorAll("#provinces > path[id]");

  for (const path of provincePaths) {
    /*
     * This black path between France and Germany is not a playable JReferee
     * province and has no corresponding Province enum value.
     */
    if (path.id === "path4603") {
      continue;
    }

    path.classList.add("province");
    path.setAttribute("tabindex", "0");
    path.setAttribute("role", "button");
    path.setAttribute("aria-label", path.id.toUpperCase());

    path.addEventListener("click", () => selectProvince(path.id));

    path.addEventListener("keydown", event => {
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        selectProvince(path.id);
      }
    });

    path.addEventListener("pointerenter", () => {
      showTooltip(path.id.toUpperCase());
    });

    path.addEventListener("pointermove", moveTooltip);
    path.addEventListener("pointerleave", hideTooltip);
  }
}

/*
 * Colors the existing Inkscape-generated circles in standard.svg's #layer5.
 *
 * Each marker has:
 * - first circle: outer colored ring
 * - second circle: white center dot
 */
function renderSupplyCenterOwners() {
  const indicatorLayer = svgRoot.querySelector("#layer5");

  if (!indicatorLayer) {
    console.warn("standard.svg is missing the #layer5 supply-center layer.");
    return;
  }

  for (const [indicatorId, province] of Object.entries(
    SUPPLY_CENTER_INDICATORS
  )) {
    const indicator = svgRoot.querySelector(
      `#${CSS.escape(indicatorId)}`
    );

    if (!indicator) {
      console.warn(
        `No SVG supply-center indicator found for ${province}: #${indicatorId}`
      );
      continue;
    }

    const circles = indicator.querySelectorAll("circle");

    if (circles.length < 2) {
      console.warn(
        `Supply-center indicator for ${province} does not contain two circles.`
      );
      continue;
    }

    const owner = board.supplyCenterOwners[province] ?? null;
    const ownerColor = owner
      ? NATION_COLORS[owner]
      : NEUTRAL_SUPPLY_CENTER_COLOR;

    if (owner && !ownerColor) {
      console.warn(
        `No supply-center color configured for nation ${owner}.`
      );
    }

    const ring = circles[0];
    const dot = circles[1];

    /*
     * The original SVG uses inline style attributes. CSS declarations in that
     * attribute override normal presentation attributes, so use style setters.
     */
    ring.style.setProperty(
      "fill",
      ownerColor ?? NEUTRAL_SUPPLY_CENTER_COLOR
    );
    ring.style.setProperty(
      "stroke",
      SUPPLY_CENTER_OUTLINE_COLOR
    );

    dot.style.setProperty(
      "fill",
      SUPPLY_CENTER_DOT_COLOR
    );
    dot.style.setProperty(
      "stroke",
      "none"
    );

    indicator.dataset.province = province;
    indicator.dataset.owner = owner ?? "NEUTRAL";
    indicator.setAttribute(
      "aria-label",
      owner
        ? `${province} supply center controlled by ${owner}`
        : `${province} neutral supply center`
    );
  }
}

function selectProvince(province) {
  selectedProvince = visibleProvinceKey(province);

  for (const path of svgRoot.querySelectorAll("#provinces > path[id]")) {
    path.classList.toggle(
      "is-selected",
      path.id === selectedProvince
    );
  }

  renderInspector(selectedProvince);
}

function clearSelection() {
  selectedProvince = null;

  if (svgRoot) {
    for (const path of svgRoot.querySelectorAll(".province")) {
      path.classList.remove("is-selected");
    }
  }

  document.querySelector("#selection-empty").hidden = false;
  document.querySelector("#province-details").hidden = true;
}

function renderTurnLabel() {
  document.querySelector("#turn-label").textContent =
    `${board.phase.replaceAll("_", " ")} ${board.year}`;
}

function renderInspector(provinceKey) {
  const matchingUnits = board.units.filter(unit => {
    return visibleProvinceKey(unit.province) === provinceKey;
  });

  const province = enumStyleProvince(provinceKey);

  const owner = board.supplyCenterOwners[province]
    ?? "Not a supply center";

  document.querySelector("#selection-empty").hidden = true;
  document.querySelector("#province-details").hidden = false;

  document.querySelector("#detail-province").textContent = province;
  document.querySelector("#detail-owner").textContent = owner;

  document.querySelector("#detail-unit").textContent =
    matchingUnits.length === 0
      ? "No unit"
      : matchingUnits
          .map(unit => {
            return `${unit.nation} ${unit.type} (${unit.province})`;
          })
          .join(", ");
}

/*
 * For now, province codes are also used as the display names. A later API
 * revision can return Province.fullName separately from Province.name().
 */
function enumStyleProvince(provinceKey) {
  const seaSpaces = new Set([
    "adr", "aeg", "bal", "bar", "bla", "bot", "eas", "eng",
    "hel", "ion", "iri", "lyo", "mao", "nao", "nth", "nwg",
    "ska", "tys", "wes"
  ]);

  if (seaSpaces.has(provinceKey)) {
    return provinceKey.toUpperCase();
  }

  return provinceKey.charAt(0).toUpperCase()
    + provinceKey.slice(1);
}

function renderUnits() {
  const unitLayer = svgRoot.querySelector("#units");

  if (!unitLayer) {
    throw new Error("standard.svg is missing the #units layer.");
  }

  unitLayer.replaceChildren();

  for (const unit of board.units) {
    const token = createUnitToken(unit);
    unitLayer.append(token);
  }
}

function createUnitToken(unit) {
  const exactLocation = keyOf(unit.province);
  const visibleLocation = visibleProvinceKey(unit.province);

  const provincePath = svgRoot.querySelector(
    `#provinces > path#${CSS.escape(visibleLocation)}`
  );

  if (!provincePath) {
    console.warn(`No SVG province path for unit at ${unit.province}.`);
    return document.createDocumentFragment();
  }

  const anchor = unitAnchor(provincePath, exactLocation);
  const group = document.createElementNS(SVG_NS, "g");

  group.classList.add("unit-token");
  group.dataset.province = unit.province;
  group.setAttribute(
    "transform",
    `translate(${anchor.x} ${anchor.y})`
  );
  group.setAttribute(
    "aria-label",
    `${unit.nation} ${unit.type} in ${unit.province}`
  );

  const body = document.createElementNS(SVG_NS, "circle");
  body.setAttribute("r", "2.6");
  body.setAttribute(
    "fill",
    NATION_COLORS[unit.nation] ?? "#ffffff"
  );

  const label = document.createElementNS(SVG_NS, "text");
  label.setAttribute("text-anchor", "middle");
  label.setAttribute("dominant-baseline", "central");
  label.setAttribute("font-size", "2.3");
  label.setAttribute("font-weight", "bold");
  label.setAttribute("fill", "#ffffff");
  label.setAttribute("pointer-events", "none");
  label.textContent = unit.type === "ARMY" ? "A" : "F";

  group.append(body, label);

  group.addEventListener("click", event => {
    event.stopPropagation();
    selectProvince(unit.province);
  });

  group.addEventListener("pointerenter", () => {
    showTooltip(
      `${unit.province}: ${unit.nation} ${unit.type}`
    );
  });

  group.addEventListener("pointermove", moveTooltip);
  group.addEventListener("pointerleave", hideTooltip);

  return group;
}

function unitAnchor(provincePath, exactLocation) {
  const box = provincePath.getBBox();
  const offset = COAST_OFFSETS[exactLocation] ?? { dx: 0, dy: 0 };

  return {
    x: box.x + (box.width / 2) + offset.dx,
    y: box.y + (box.height / 2) + offset.dy
  };
}

function showTooltip(message) {
  const tooltip = document.querySelector("#tooltip");
  tooltip.textContent = message;
  tooltip.hidden = false;
}

function moveTooltip(event) {
  const tooltip = document.querySelector("#tooltip");
  tooltip.style.left = `${event.clientX + 12}px`;
  tooltip.style.top = `${event.clientY + 12}px`;
}

function hideTooltip() {
  document.querySelector("#tooltip").hidden = true;
}

startViewer().catch(error => {
  console.error(error);

  const turnLabel = document.querySelector("#turn-label");

  if (turnLabel) {
    turnLabel.textContent = "Unable to load board";
  }
});